{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "057980c8-ec70-4fbd-a7ea-ddd745732b57",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "test_drift_detector.py\n",
    "----------------------\n",
    "Unit tests สำหรับ Hybrid DriftDetector\n",
    "\"\"\"\n",
    "\n",
    "import pytest\n",
    "import pandas as pd\n",
    "from project.models.drift_detector import DriftDetector\n",
    "\n",
    "\n",
    "@pytest.fixture\n",
    "def sample_data():\n",
    "    # Reference data (distribution เดิม)\n",
    "    df_ref = pd.DataFrame({\n",
    "        \"feature1\": [0.1, 0.2, 0.3, 0.4],\n",
    "        \"feature2\": [1, 2, 3, 4]\n",
    "    })\n",
    "    # New data (distribution เปลี่ยน)\n",
    "    df_new = pd.DataFrame({\n",
    "        \"feature1\": [0.6, 0.7, 0.8, 0.9],\n",
    "        \"feature2\": [5, 6, 7, 8]\n",
    "    })\n",
    "    return df_ref, df_new\n",
    "\n",
    "\n",
    "def test_performance_drift_detection():\n",
    "    detector = DriftDetector(env=\"dev\")\n",
    "\n",
    "    # baseline สมมติ\n",
    "    detector.save_baseline({\"accuracy\": 0.9, \"f1\": 0.88, \"rmse\": 0.1})\n",
    "\n",
    "    # ผลใหม่\n",
    "    y_true = [0, 1, 0, 1, 0, 1]\n",
    "    y_pred = [0, 1, 1, 1, 0, 0]\n",
    "\n",
    "    result = detector.detect_performance_drift(y_true, y_pred)\n",
    "\n",
    "    assert \"current_metrics\" in result\n",
    "    assert \"baseline_metrics\" in result\n",
    "    assert \"drift_flags\" in result\n",
    "    assert isinstance(result[\"drift_detected\"], bool)\n",
    "\n",
    "\n",
    "def test_data_drift_detection(sample_data):\n",
    "    df_ref, df_new = sample_data\n",
    "    detector = DriftDetector(env=\"dev\")\n",
    "\n",
    "    result = detector.detect_data_drift(df_ref, df_new)\n",
    "\n",
    "    assert \"overall_drift\" in result\n",
    "    assert \"details\" in result\n",
    "    assert isinstance(result[\"overall_drift\"], bool)\n",
    "\n",
    "\n",
    "def test_data_drift_empty_input():\n",
    "    detector = DriftDetector(env=\"dev\")\n",
    "\n",
    "    df_ref = pd.DataFrame()\n",
    "    df_new = pd.DataFrame()\n",
    "\n",
    "    result = detector.detect_data_drift(df_ref, df_new)\n",
    "\n",
    "    assert result[\"overall_drift\"] is False\n",
    "    assert result[\"details\"] == {}"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
